### ISSUE TITLE
Version mismatch between github and luarocks?

### ISSUE THREAD

**Issue by 25A0** [jgm/lcmark#6]
It appears that the fix provided in #4 is not actually included in version 0.29.0-4 on luarocks.org. I was trying to use lcmark with luajit, and ran into errors that were supposedly fixed by #4 .

Upon closer inspection, it appears that version 0.29.0-4 on luarocks is different from what is in this github repo. I downloaded the 0.29.0-4 [source rock from luarocks](https://luarocks.org/manifests/jgm/lcmark-0.29.0-4.src.rock), and while the rockspec declares to be version 0.29.0-4, the source code differs from what is tagged as 0.29.0-4 here on github: The fix provided in #4 is missing, the REVISION variable in the Makefile is still set to 1, and the tag key in the rockspec file is set to 0.29.0, rather than 0.29.0-4.

In case it helps, I noticed that rockspec.in includes the revision in the version key, but not in the tag key:

https://github.com/jgm/lcmark/blob/9f7740dbf0ac4c965a2a26d6b4278a1168788381/rockspec.in#L1-L6

**Comment by jgm** [comment]
OK, hopefully fixed with a 0.29.0-5 release (including fix to rockspec.in).

**Comment by 25A0** [comment]
Yes, that fixed it. Thanks a lot for the quick response!
